# Simple Multi-stage Pipeline with Deployment Slots Demo
# Stages: Build → UAT → Production Staging → Slot Swap

trigger:
- main

variables:
  buildConfiguration: 'Release'
  azureServiceConnection: 'azure-service-connection' # Update with your service connection name
  
  # Update these after creating your App Services
  uatWebAppName: 'tailspin-uat-webapp'
  prodWebAppName: 'tailspin-prod-webapp'
  resourceGroupName: 'rg-tailspin-demo'

stages:
- stage: Build
  displayName: 'Build App'
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
    
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: 'Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj'
        arguments: '--configuration $(buildConfiguration)'
    
    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        projects: 'Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
    
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: webapp

- stage: DeployUAT
  displayName: 'Deploy to UAT'
  dependsOn: Build
  jobs:
  - deployment: DeployUAT
    environment: 'UAT'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy to UAT'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appType: 'webApp'
              appName: '$(uatWebAppName)'
              package: '$(Pipeline.Workspace)/webapp/Tailspin.SpaceGame.Web.zip'

- stage: DeployProdStaging
  displayName: 'Deploy to Prod Staging Slot'
  dependsOn: DeployUAT
  jobs:
  - job: ManualValidationUAT
    displayName: 'Manual Validation - UAT Testing Complete'
    pool: server
    steps:
    - task: ManualValidation@0
      displayName: 'Approve UAT Testing Results'
      inputs:
        notifyUsers: 'venn.d.dela.pena@accenture.com' # Update with your actual notification email
        instructions: 'Please validate UAT deployment at: https://tailspin-uat-webapp.azurewebsites.net'
        onTimeout: 'reject'
  
  - deployment: DeployProdStaging
    dependsOn: ManualValidationUAT
    environment: 'Production-Staging'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy to Staging Slot'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appType: 'webApp'
              appName: '$(prodWebAppName)'
              deployToSlotOrASE: true
              resourceGroupName: '$(resourceGroupName)'
              slotName: 'staging'
              package: '$(Pipeline.Workspace)/webapp/Tailspin.SpaceGame.Web.zip'

- stage: SwapToProduction
  displayName: 'Swap to Production'
  dependsOn: DeployProdStaging
  jobs:
  - job: ManualValidationStaging
    displayName: 'Manual Validation - Staging Testing Complete'
    pool: server
    steps:
    - task: ManualValidation@0
      displayName: 'Approve Production Slot Swap'
      inputs:
        notifyUsers: 'venn.d.dela.pena@accenture.com' # Update with your actual notification email
        instructions: 'Please validate staging deployment at: https://tailspin-prod-webapp-staging.azurewebsites.net'
        onTimeout: 'reject'
  
  - deployment: SwapSlots
    dependsOn: ManualValidationStaging
    environment: 'Production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceManage@0
            displayName: 'Swap Staging to Production'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              action: 'Swap Slots'
              webAppName: '$(prodWebAppName)'
              resourceGroupName: '$(resourceGroupName)'
              sourceSlot: 'staging'